[package]
edition = "2024"
name    = "affine_native"
version = "0.0.0"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
affine_common = { workspace = true, features = ["hashcash"] }
affine_media_capture = { path = "./media_capture" }
affine_nbstore = { workspace = true, features = ["napi"] }
affine_sqlite_v1 = { path = "./sqlite_v1" }
napi = { workspace = true }
napi-derive = { workspace = true }
once_cell = { workspace = true }
sqlx = { workspace = true, default-features = false, features = [
  "chrono",
  "macros",
  "migrate",
  "runtime-tokio",
  "sqlite",
  "tls-rustls",
] }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }

[target.'cfg(not(target_os = "linux"))'.dependencies]
mimalloc = { workspace = true }

[target.'cfg(all(target_os = "linux", not(target_arch = "arm")))'.dependencies]
mimalloc = { workspace = true, features = ["local_dynamic_tls"] }

[dev-dependencies]
chrono     = { workspace = true }
serde_json = { workspace = true }
uuid       = { workspace = true }

[build-dependencies]
napi-build = { workspace = true }
sqlx = { workspace = true, default-features = false, features = [
  "chrono",
  "json",
  "macros",
  "migrate",
  "runtime-tokio",
  "sqlite",
  "tls-rustls",
] }
tokio = { workspace = true, features = ["full"] }
