apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.docService.name }}
  labels:
    {{- include "front.labels" . | nindent 4 }}
  {{- with .Values.services.doc.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.services.doc.type }}
  ports:
    - port: {{ .Values.global.docService.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "front.selectorLabels" . | nindent 4 }}
