apiVersion: v2
name: front
description: AFFiNE front server
type: application
version: 0.0.0
appVersion: "0.26.3"
dependencies:
  - name: gcloud-sql-proxy
    version: 0.0.0
    repository: "file://../gcloud-sql-proxy"
    condition: .global.database.gcloud.enabled
